
package com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2017-09-01T11:27:22.331+05:30
 * Generated source version: 2.7.7
 */

@WebFault(name = "CalculateSupplierQuoteFault", targetNamespace = "http://www.orange.com/Meerkat/Interfaces/ManageSupplierQuote/RequestForQuotation/v1/message")
public class CalculateSupplierQuoteFault extends Exception {
    
    private com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.message.CalculateSupplierQuoteFault calculateSupplierQuoteFault;

    public CalculateSupplierQuoteFault() {
        super();
    }
    
    public CalculateSupplierQuoteFault(String message) {
        super(message);
    }
    
    public CalculateSupplierQuoteFault(String message, Throwable cause) {
        super(message, cause);
    }

    public CalculateSupplierQuoteFault(String message, com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.message.CalculateSupplierQuoteFault calculateSupplierQuoteFault) {
        super(message);
        this.calculateSupplierQuoteFault = calculateSupplierQuoteFault;
    }

    public CalculateSupplierQuoteFault(String message, com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.message.CalculateSupplierQuoteFault calculateSupplierQuoteFault, Throwable cause) {
        super(message, cause);
        this.calculateSupplierQuoteFault = calculateSupplierQuoteFault;
    }

    public com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.message.CalculateSupplierQuoteFault getFaultInfo() {
        return this.calculateSupplierQuoteFault;
    }
}
