package com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2017-09-01T11:27:22.409+05:30
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://www.orange.com/Meerkat/Interfaces/ManageSupplierQuote/RequestForQuotation/v1", name = "ManageSupplierQuoteRequestForQuotation")
@XmlSeeAlso({com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.ObjectFactory.class, com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.ObjectFactory.class, com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.ObjectFactory.class, com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.errors.ObjectFactory.class, com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.message.ObjectFactory.class, com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.in.ObjectFactory.class})
public interface ManageSupplierQuoteRequestForQuotation {

    @WebResult(name = "SupplierQuoteResp", targetNamespace = "")
    @RequestWrapper(localName = "CalculateSupplierQuote", targetNamespace = "http://www.orange.com/Meerkat/Interfaces/ManageSupplierQuote/RequestForQuotation/v1/message", className = "com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.message.CalculateSupplierQuote")
    @WebMethod(operationName = "CalculateSupplierQuote", action = "http://www.orange.com/Meerkat/Interfaces/ManageSupplierQuote/RequestForQuotation/v1/CalculateSupplierQuote")
    @ResponseWrapper(localName = "CalculateSupplierQuoteResponse", targetNamespace = "http://www.orange.com/Meerkat/Interfaces/ManageSupplierQuote/RequestForQuotation/v1/message", className = "com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.message.CalculateSupplierQuoteResponse")
    public com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.SupplierQuoteViewForCalculateSupplierQuoteResponse calculateSupplierQuote(
        @WebParam(name = "SupplierQuote", targetNamespace = "")
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.SupplierQuoteViewForCalculateSupplierQuoteRequest supplierQuote
    ) throws CalculateSupplierQuoteFault;

    @WebResult(name = "SupplierQuoteResp", targetNamespace = "")
    @RequestWrapper(localName = "UpdateSupplierQuote", targetNamespace = "http://www.orange.com/Meerkat/Interfaces/ManageSupplierQuote/RequestForQuotation/v1/message", className = "com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.message.UpdateSupplierQuote")
    @WebMethod(operationName = "UpdateSupplierQuote", action = "http://www.orange.com/Meerkat/Interfaces/ManageSupplierQuote/RequestForQuotation/v1/UpdateSupplierQuote")
    @ResponseWrapper(localName = "UpdateSupplierQuoteResponse", targetNamespace = "http://www.orange.com/Meerkat/Interfaces/ManageSupplierQuote/RequestForQuotation/v1/message", className = "com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.message.UpdateSupplierQuoteResponse")
    public java.util.List<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.SupplierQuoteViewForUpdateSupplierQuoteResponse> updateSupplierQuote(
        @WebParam(name = "SupplierQuote", targetNamespace = "")
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.in.SupplierQuoteViewForUpdateSupplierQuoteRequest supplierQuote
    ) throws UpdateSupplierQuoteFault;
}
