
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2017-09-01T11:27:22.393+05:30
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "ManageSupplierQuoteRequestForQuotation_Meerkat",
                      portName = "ManageSupplierQuoteRequestForQuotationPort",
                      targetNamespace = "http://www.orange.com/Meerkat/Interfaces/ManageSupplierQuote/RequestForQuotation/v1",
                      wsdlLocation = "file:E:/TASKS/webservice3/MeerkatWebservice/MeerkatWebservice/WebContent/ManageSupplierQuoteRequestForQuotationPort.wsdl",
                      endpointInterface = "com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ManageSupplierQuoteRequestForQuotation")
                      
public class ManageSupplierQuoteRequestForQuotationImpl implements ManageSupplierQuoteRequestForQuotation {

    private static final Logger LOG = Logger.getLogger(ManageSupplierQuoteRequestForQuotationImpl.class.getName());

    /* (non-Javadoc)
     * @see com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ManageSupplierQuoteRequestForQuotation#calculateSupplierQuote(com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.SupplierQuoteViewForCalculateSupplierQuoteRequest  supplierQuote )*
     */
    public com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.SupplierQuoteViewForCalculateSupplierQuoteResponse calculateSupplierQuote(com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.SupplierQuoteViewForCalculateSupplierQuoteRequest supplierQuote) throws CalculateSupplierQuoteFault    { 
        LOG.info("Executing operation calculateSupplierQuote");
        System.out.println(supplierQuote);
        try {
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.SupplierQuoteViewForCalculateSupplierQuoteResponse _return = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.SupplierQuoteViewForCalculateSupplierQuoteResponse();
            _return.setCreationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-01T11:27:22.409+05:30"));
            _return.setLocalBusinessOpportunityType("LocalBusinessOpportunityType-206361671");
            _return.setLocalAccessType("LocalAccessType1794915949");
            java.util.List<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.QuoteItem> _returnQuoteItem = new java.util.ArrayList<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.QuoteItem>();
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.QuoteItem _returnQuoteItemVal1 = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.QuoteItem();
            _returnQuoteItemVal1.setLocalRefId("GANESHPOCTEST0001");
            _returnQuoteItemVal1.setQuoteItemID("GANESHPOCTEST0001");
            _returnQuoteItemVal1.setLocalMeerkatQuoteItemID("LocalMeerkatQuoteItemID-1116124556");
            _returnQuoteItemVal1.setLocalExternalQuoteItemID("LocalExternalQuoteItemID-1713988269");
            _returnQuoteItemVal1.setLocalEligibilityresponse(false);
            _returnQuoteItemVal1.setLocalPricingresponse(true);
            _returnQuoteItemVal1.setLocalValidityStartDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-01T11:27:22.409+05:30"));
            _returnQuoteItemVal1.setLocalValidityEndDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-01T11:27:22.409+05:30"));
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.LocalResponseType _returnQuoteItemVal1LocalResponseType = com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.LocalResponseType.ACTUAL;
            _returnQuoteItemVal1.setLocalResponseType(_returnQuoteItemVal1LocalResponseType);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.LocalResponseStatus _returnQuoteItemVal1LocalResponseStatus = com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.LocalResponseStatus.IN_PROGRESS;
            _returnQuoteItemVal1.setLocalResponseStatus(_returnQuoteItemVal1LocalResponseStatus);
            _returnQuoteItemVal1.setComments("Comments-750308642");
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.OfferSpecification _returnQuoteItemVal1OfferSpecification = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.OfferSpecification();
            _returnQuoteItemVal1OfferSpecification.setOfferSpecificationCode("OfferSpecificationCode-1092073037");
            _returnQuoteItemVal1OfferSpecification.setOfferSpecificationLabel("OfferSpecificationLabel827841134");
            _returnQuoteItemVal1OfferSpecification.setNumberOfIP("NumberOfIP1216286602");
            _returnQuoteItemVal1OfferSpecification.setTypeOfIP("TypeOfIP-566694852");
            _returnQuoteItemVal1OfferSpecification.setAreaCovered("AreaCovered427127956");
            _returnQuoteItemVal1OfferSpecification.setIspProductName("IspProductName-295160852");
            _returnQuoteItemVal1OfferSpecification.setPstnResponsibility("PstnResponsibility1585429826");
            _returnQuoteItemVal1OfferSpecification.setServiceAvailability("ServiceAvailability1798389925");
            _returnQuoteItemVal1OfferSpecification.setCarrierQuoteRef("CarrierQuoteRef1183536148");
            _returnQuoteItemVal1OfferSpecification.setMttr("Mttr-398487464");
            _returnQuoteItemVal1OfferSpecification.setContentionRatio("ContentionRatio531910820");
            _returnQuoteItemVal1OfferSpecification.setLtc("Ltc-523317691");
            _returnQuoteItemVal1OfferSpecification.setTrafficRestrictions("TrafficRestrictions148661378");
            _returnQuoteItemVal1OfferSpecification.setDemarcationInterface("DemarcationInterface-2108555738");
            _returnQuoteItemVal1OfferSpecification.setOrangeCpeResp("OrangeCpeResp1724801398");
            _returnQuoteItemVal1OfferSpecification.setOfferId("OfferId2113897060");
            _returnQuoteItemVal1OfferSpecification.setOfferStatus("OfferStatus174790948");
            _returnQuoteItemVal1OfferSpecification.setOfferGrade("OfferGrade766124871");
            _returnQuoteItemVal1OfferSpecification.setSymmetry("Symmetry1720278059");
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.Currency _returnQuoteItemVal1OfferSpecificationCurrency = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.Currency();
            _returnQuoteItemVal1OfferSpecificationCurrency.setCurrencyCode("CurrencyCode1058563580");
            _returnQuoteItemVal1OfferSpecification.setCurrency(_returnQuoteItemVal1OfferSpecificationCurrency);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.CommitmentSpecification _returnQuoteItemVal1OfferSpecificationCommitmentSpecification = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.CommitmentSpecification();
            _returnQuoteItemVal1OfferSpecificationCommitmentSpecification.setDurationValue(0.7262105358044958);
            _returnQuoteItemVal1OfferSpecificationCommitmentSpecification.setDurationUnit("DurationUnit501708423");
            _returnQuoteItemVal1OfferSpecification.setCommitmentSpecification(_returnQuoteItemVal1OfferSpecificationCommitmentSpecification);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.ProductSpecification _returnQuoteItemVal1OfferSpecificationProductSpecification = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.ProductSpecification();
            _returnQuoteItemVal1OfferSpecificationProductSpecification.setLocalPricingResultType("LocalPricingResultType-557506678");
            _returnQuoteItemVal1OfferSpecificationProductSpecification.setProductSpecificationType("ProductSpecificationType1724198186");
            java.util.List<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.FunctionSpecification> _returnQuoteItemVal1OfferSpecificationProductSpecificationFunctionSpecification = new java.util.ArrayList<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.FunctionSpecification>();
            _returnQuoteItemVal1OfferSpecificationProductSpecification.getFunctionSpecification().addAll(_returnQuoteItemVal1OfferSpecificationProductSpecificationFunctionSpecification);
            java.util.List<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.TariffSpecification> _returnQuoteItemVal1OfferSpecificationProductSpecificationTariffSpecification = new java.util.ArrayList<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.TariffSpecification>();
            _returnQuoteItemVal1OfferSpecificationProductSpecification.getTariffSpecification().addAll(_returnQuoteItemVal1OfferSpecificationProductSpecificationTariffSpecification);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.SubNetwork _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetwork = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.SubNetwork();
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetwork.setSubNetworkID("SubNetworkID-1705436093");
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.SubNetworkRole _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkSubNetworkRole = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.SubNetworkRole();
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkSubNetworkRole.setSubNetworkRoleName("SubNetworkRoleName-147404151");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetwork.setSubNetworkRole(_returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkSubNetworkRole);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.AddressSubNetwork _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddress = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.AddressSubNetwork();
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddress.setApartmentNumber("ApartmentNumber-1551024599");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddress.setStaircaseNumber("StaircaseNumber315740735");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddress.setFloorNumber("FloorNumber226480147");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddress.setBuildingName("BuildingName-678249596");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddress.setResidenceName("ResidenceName-1342529061");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddress.setLocality("Locality432634417");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddress.setPostalCode("PostalCode1023058121");
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.GeographicCoordinatesSubNetwork _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressGeographicCoordinates = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.GeographicCoordinatesSubNetwork();
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressGeographicCoordinates.setGeocodeX("GeocodeX1228147086");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressGeographicCoordinates.setGeocodeY("GeocodeY-1873963734");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressGeographicCoordinates.setGeocodingSystems("GeocodingSystems1114192196");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddress.setGeographicCoordinates(_returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressGeographicCoordinates);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.StreetSubNetwork _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressStreet = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.StreetSubNetwork();
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressStreet.setStreetNumber("StreetNumber1150869856");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressStreet.setStreetLetter("StreetLetter-752601314");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressStreet.setStreetType("StreetType-1436521489");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressStreet.setStreetName("StreetName645772425");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddress.setStreet(_returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressStreet);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.CitySubNetwork _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressCity = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.CitySubNetwork();
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressCity.setCityName("CityName-173208246");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddress.setCity(_returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressCity);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.StateSubNetwork _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressState = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.StateSubNetwork();
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressState.setStateName("StateName319759600");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddress.setState(_returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressState);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.CountrySubNetwork _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressCountry = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.CountrySubNetwork();
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressCountry.setCountryName("CountryName-64636047");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddress.setCountry(_returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddressCountry);
            _returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetwork.setLocalAddress(_returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkLocalAddress);
            _returnQuoteItemVal1OfferSpecificationProductSpecification.setSubNetwork(_returnQuoteItemVal1OfferSpecificationProductSpecificationSubNetwork);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.EligibilityDecision _returnQuoteItemVal1OfferSpecificationProductSpecificationLocalEligibilityDecision = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.EligibilityDecision();
            _returnQuoteItemVal1OfferSpecificationProductSpecificationLocalEligibilityDecision.setLocalDecisionCode("LocalDecisionCode-1082983837");
            _returnQuoteItemVal1OfferSpecificationProductSpecificationLocalEligibilityDecision.setLocalDecisionComments("LocalDecisionComments-24997725");
            _returnQuoteItemVal1OfferSpecificationProductSpecification.setLocalEligibilityDecision(_returnQuoteItemVal1OfferSpecificationProductSpecificationLocalEligibilityDecision);
            _returnQuoteItemVal1OfferSpecification.setProductSpecification(_returnQuoteItemVal1OfferSpecificationProductSpecification);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.Catalogue _returnQuoteItemVal1OfferSpecificationCatalogue = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.Catalogue();
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.Operator _returnQuoteItemVal1OfferSpecificationCatalogueOperator = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.Operator();
            _returnQuoteItemVal1OfferSpecificationCatalogueOperator.setName("Name70780972");
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.Party _returnQuoteItemVal1OfferSpecificationCatalogueOperatorParty = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.Party();
            _returnQuoteItemVal1OfferSpecificationCatalogueOperatorParty.setPartyID("PartyID-2008449103");
            _returnQuoteItemVal1OfferSpecificationCatalogueOperator.setParty(_returnQuoteItemVal1OfferSpecificationCatalogueOperatorParty);
            _returnQuoteItemVal1OfferSpecificationCatalogue.setOperator(_returnQuoteItemVal1OfferSpecificationCatalogueOperator);
            _returnQuoteItemVal1OfferSpecification.setCatalogue(_returnQuoteItemVal1OfferSpecificationCatalogue);
            _returnQuoteItemVal1.setOfferSpecification(_returnQuoteItemVal1OfferSpecification);
            _returnQuoteItem.add(_returnQuoteItemVal1);
            _return.getQuoteItem().addAll(_returnQuoteItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new CalculateSupplierQuoteFault("CalculateSupplierQuoteFault...");
    }

    /* (non-Javadoc)
     * @see com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ManageSupplierQuoteRequestForQuotation#updateSupplierQuote(com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.in.SupplierQuoteViewForUpdateSupplierQuoteRequest  supplierQuote )*
     */
    public java.util.List<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.SupplierQuoteViewForUpdateSupplierQuoteResponse> updateSupplierQuote(com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.in.SupplierQuoteViewForUpdateSupplierQuoteRequest supplierQuote) throws UpdateSupplierQuoteFault    { 
        LOG.info("Executing operation updateSupplierQuote");
        System.out.println(supplierQuote);
        try {
            java.util.List<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.SupplierQuoteViewForUpdateSupplierQuoteResponse> _return = new java.util.ArrayList<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.SupplierQuoteViewForUpdateSupplierQuoteResponse>();
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.SupplierQuoteViewForUpdateSupplierQuoteResponse _returnVal1 = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.SupplierQuoteViewForUpdateSupplierQuoteResponse();
            _returnVal1.setCreationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-01T11:27:22.409+05:30"));
            _returnVal1.setLocalBusinessOpportunityType("LocalBusinessOpportunityType-1343561915");
            _returnVal1.setLocalAccessType("LocalAccessType-747937878");
            java.util.List<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.QuoteItem> _returnVal1QuoteItem = new java.util.ArrayList<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.QuoteItem>();
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.QuoteItem _returnVal1QuoteItemVal1 = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.QuoteItem();
            _returnVal1QuoteItemVal1.setLocalRefId("LocalRefId-1488642362");
            _returnVal1QuoteItemVal1.setQuoteItemID("QuoteItemID-802242045");
            _returnVal1QuoteItemVal1.setLocalMeerkatQuoteItemID("LocalMeerkatQuoteItemID14017216");
            _returnVal1QuoteItemVal1.setLocalExternalQuoteItemID("LocalExternalQuoteItemID667619692");
            _returnVal1QuoteItemVal1.setLocalEligibilityresponse(false);
            _returnVal1QuoteItemVal1.setLocalPricingresponse(false);
            _returnVal1QuoteItemVal1.setLocalValidityStartDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-01T11:27:22.409+05:30"));
            _returnVal1QuoteItemVal1.setLocalValidityEndDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-01T11:27:22.409+05:30"));
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.LocalResponseType _returnVal1QuoteItemVal1LocalResponseType = com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.LocalResponseType.ACTUAL;
            _returnVal1QuoteItemVal1.setLocalResponseType(_returnVal1QuoteItemVal1LocalResponseType);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.LocalResponseStatus _returnVal1QuoteItemVal1LocalResponseStatus = com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.LocalResponseStatus.COMPLETE;
            _returnVal1QuoteItemVal1.setLocalResponseStatus(_returnVal1QuoteItemVal1LocalResponseStatus);
            _returnVal1QuoteItemVal1.setComments("Comments-1784883187");
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.OfferSpecification _returnVal1QuoteItemVal1OfferSpecification = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.OfferSpecification();
            _returnVal1QuoteItemVal1OfferSpecification.setOfferSpecificationCode("OfferSpecificationCode-1637451526");
            _returnVal1QuoteItemVal1OfferSpecification.setOfferSpecificationLabel("OfferSpecificationLabel1761219333");
            _returnVal1QuoteItemVal1OfferSpecification.setNumberOfIP("NumberOfIP-1714831748");
            _returnVal1QuoteItemVal1OfferSpecification.setTypeOfIP("TypeOfIP303788463");
            _returnVal1QuoteItemVal1OfferSpecification.setAreaCovered("AreaCovered-176586863");
            _returnVal1QuoteItemVal1OfferSpecification.setIspProductName("IspProductName1342973705");
            _returnVal1QuoteItemVal1OfferSpecification.setPstnResponsibility("PstnResponsibility1405027293");
            _returnVal1QuoteItemVal1OfferSpecification.setServiceAvailability("ServiceAvailability147228964");
            _returnVal1QuoteItemVal1OfferSpecification.setCarrierQuoteRef("CarrierQuoteRef-623329787");
            _returnVal1QuoteItemVal1OfferSpecification.setMttr("Mttr384199647");
            _returnVal1QuoteItemVal1OfferSpecification.setContentionRatio("ContentionRatio-1717482422");
            _returnVal1QuoteItemVal1OfferSpecification.setLtc("Ltc-2133330684");
            _returnVal1QuoteItemVal1OfferSpecification.setTrafficRestrictions("TrafficRestrictions-1075779925");
            _returnVal1QuoteItemVal1OfferSpecification.setDemarcationInterface("DemarcationInterface1127308427");
            _returnVal1QuoteItemVal1OfferSpecification.setOrangeCpeResp("OrangeCpeResp1118607166");
            _returnVal1QuoteItemVal1OfferSpecification.setOfferId("OfferId-834549169");
            _returnVal1QuoteItemVal1OfferSpecification.setOfferStatus("OfferStatus-1170990365");
            _returnVal1QuoteItemVal1OfferSpecification.setOfferGrade("OfferGrade1341065856");
            _returnVal1QuoteItemVal1OfferSpecification.setSymmetry("Symmetry1634061185");
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.Currency _returnVal1QuoteItemVal1OfferSpecificationCurrency = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.Currency();
            _returnVal1QuoteItemVal1OfferSpecificationCurrency.setCurrencyCode("CurrencyCode-1112722291");
            _returnVal1QuoteItemVal1OfferSpecification.setCurrency(_returnVal1QuoteItemVal1OfferSpecificationCurrency);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.CommitmentSpecification _returnVal1QuoteItemVal1OfferSpecificationCommitmentSpecification = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.CommitmentSpecification();
            _returnVal1QuoteItemVal1OfferSpecificationCommitmentSpecification.setDurationValue(0.6820722973759924);
            _returnVal1QuoteItemVal1OfferSpecificationCommitmentSpecification.setDurationUnit("DurationUnit-2119362407");
            _returnVal1QuoteItemVal1OfferSpecification.setCommitmentSpecification(_returnVal1QuoteItemVal1OfferSpecificationCommitmentSpecification);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.ProductSpecification _returnVal1QuoteItemVal1OfferSpecificationProductSpecification = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.ProductSpecification();
            _returnVal1QuoteItemVal1OfferSpecificationProductSpecification.setLocalPricingResultType("LocalPricingResultType-187945929");
            _returnVal1QuoteItemVal1OfferSpecificationProductSpecification.setProductSpecificationType("ProductSpecificationType-1713130516");
            java.util.List<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.FunctionSpecification> _returnVal1QuoteItemVal1OfferSpecificationProductSpecificationFunctionSpecification = new java.util.ArrayList<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.FunctionSpecification>();
            _returnVal1QuoteItemVal1OfferSpecificationProductSpecification.getFunctionSpecification().addAll(_returnVal1QuoteItemVal1OfferSpecificationProductSpecificationFunctionSpecification);
            java.util.List<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.TariffSpecification> _returnVal1QuoteItemVal1OfferSpecificationProductSpecificationTariffSpecification = new java.util.ArrayList<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.TariffSpecification>();
            _returnVal1QuoteItemVal1OfferSpecificationProductSpecification.getTariffSpecification().addAll(_returnVal1QuoteItemVal1OfferSpecificationProductSpecificationTariffSpecification);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.SubNetwork _returnVal1QuoteItemVal1OfferSpecificationProductSpecificationSubNetwork = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.SubNetwork();
            _returnVal1QuoteItemVal1OfferSpecificationProductSpecificationSubNetwork.setSubNetworkID("SubNetworkID-49883876");
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.SubNetworkRole _returnVal1QuoteItemVal1OfferSpecificationProductSpecificationSubNetworkSubNetworkRole = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.SubNetworkRole();
            _returnVal1QuoteItemVal1OfferSpecificationProductSpecificationSubNetworkSubNetworkRole.setSubNetworkRoleName("SubNetworkRoleName1175485312");
            _returnVal1QuoteItemVal1OfferSpecificationProductSpecificationSubNetwork.setSubNetworkRole(_returnVal1QuoteItemVal1OfferSpecificationProductSpecificationSubNetworkSubNetworkRole);
            _returnVal1QuoteItemVal1OfferSpecificationProductSpecification.setSubNetwork(_returnVal1QuoteItemVal1OfferSpecificationProductSpecificationSubNetwork);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.EligibilityDecision _returnVal1QuoteItemVal1OfferSpecificationProductSpecificationLocalEligibilityDecision = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.EligibilityDecision();
            _returnVal1QuoteItemVal1OfferSpecificationProductSpecificationLocalEligibilityDecision.setLocalDecisionCode("LocalDecisionCode2141564757");
            _returnVal1QuoteItemVal1OfferSpecificationProductSpecificationLocalEligibilityDecision.setLocalDecisionComments("LocalDecisionComments-1537451300");
            _returnVal1QuoteItemVal1OfferSpecificationProductSpecification.setLocalEligibilityDecision(_returnVal1QuoteItemVal1OfferSpecificationProductSpecificationLocalEligibilityDecision);
            _returnVal1QuoteItemVal1OfferSpecification.setProductSpecification(_returnVal1QuoteItemVal1OfferSpecificationProductSpecification);
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.Catalogue _returnVal1QuoteItemVal1OfferSpecificationCatalogue = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.Catalogue();
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.Operator _returnVal1QuoteItemVal1OfferSpecificationCatalogueOperator = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.Operator();
            _returnVal1QuoteItemVal1OfferSpecificationCatalogueOperator.setName("Name-438167809");
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.Party _returnVal1QuoteItemVal1OfferSpecificationCatalogueOperatorParty = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.usq.out.Party();
            _returnVal1QuoteItemVal1OfferSpecificationCatalogueOperatorParty.setPartyID("PartyID-193635690");
            _returnVal1QuoteItemVal1OfferSpecificationCatalogueOperator.setParty(_returnVal1QuoteItemVal1OfferSpecificationCatalogueOperatorParty);
            _returnVal1QuoteItemVal1OfferSpecificationCatalogue.setOperator(_returnVal1QuoteItemVal1OfferSpecificationCatalogueOperator);
            _returnVal1QuoteItemVal1OfferSpecification.setCatalogue(_returnVal1QuoteItemVal1OfferSpecificationCatalogue);
            _returnVal1QuoteItemVal1.setOfferSpecification(_returnVal1QuoteItemVal1OfferSpecification);
            _returnVal1QuoteItem.add(_returnVal1QuoteItemVal1);
            _returnVal1.getQuoteItem().addAll(_returnVal1QuoteItem);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UpdateSupplierQuoteFault("UpdateSupplierQuoteFault...");
    }

}
