package com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2017-09-01T11:27:22.425+05:30
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "ManageSupplierQuoteRequestForQuotation_Meerkat", 
                  wsdlLocation = "file:E:/TASKS/webservice3/MeerkatWebservice/MeerkatWebservice/WebContent/ManageSupplierQuoteRequestForQuotationPort.wsdl",
                  targetNamespace = "http://www.orange.com/Meerkat/Interfaces/ManageSupplierQuote/RequestForQuotation/v1") 
public class ManageSupplierQuoteRequestForQuotationMeerkat extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.orange.com/Meerkat/Interfaces/ManageSupplierQuote/RequestForQuotation/v1", "ManageSupplierQuoteRequestForQuotation_Meerkat");
    public final static QName ManageSupplierQuoteRequestForQuotationPort = new QName("http://www.orange.com/Meerkat/Interfaces/ManageSupplierQuote/RequestForQuotation/v1", "ManageSupplierQuoteRequestForQuotationPort");
    static {
        URL url = null;
        try {
            url = new URL("file:E:/TASKS/webservice3/MeerkatWebservice/MeerkatWebservice/WebContent/ManageSupplierQuoteRequestForQuotationPort.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ManageSupplierQuoteRequestForQuotationMeerkat.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:E:/TASKS/webservice3/MeerkatWebservice/MeerkatWebservice/WebContent/ManageSupplierQuoteRequestForQuotationPort.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ManageSupplierQuoteRequestForQuotationMeerkat(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ManageSupplierQuoteRequestForQuotationMeerkat(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManageSupplierQuoteRequestForQuotationMeerkat() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ManageSupplierQuoteRequestForQuotationMeerkat(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ManageSupplierQuoteRequestForQuotationMeerkat(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ManageSupplierQuoteRequestForQuotationMeerkat(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ManageSupplierQuoteRequestForQuotation
     */
    @WebEndpoint(name = "ManageSupplierQuoteRequestForQuotationPort")
    public ManageSupplierQuoteRequestForQuotation getManageSupplierQuoteRequestForQuotationPort() {
        return super.getPort(ManageSupplierQuoteRequestForQuotationPort, ManageSupplierQuoteRequestForQuotation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManageSupplierQuoteRequestForQuotation
     */
    @WebEndpoint(name = "ManageSupplierQuoteRequestForQuotationPort")
    public ManageSupplierQuoteRequestForQuotation getManageSupplierQuoteRequestForQuotationPort(WebServiceFeature... features) {
        return super.getPort(ManageSupplierQuoteRequestForQuotationPort, ManageSupplierQuoteRequestForQuotation.class, features);
    }

}
