
package com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.EmailAddress;
import com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.FunctionSpecification;
import com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.FunctionValueSpecification;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2017-08-30T17:02:05.579+05:30
 * Generated source version: 2.7.7
 * 
 */
public final class ManageSupplierQuoteRequestForQuotation_ManageSupplierQuoteRequestForQuotationPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.orange.com/Meerkat/Interfaces/ManageSupplierQuote/RequestForQuotation/v1", "ManageSupplierQuoteRequestForQuotation_Meerkat");

    private ManageSupplierQuoteRequestForQuotation_ManageSupplierQuoteRequestForQuotationPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ManageSupplierQuoteRequestForQuotationMeerkat.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ManageSupplierQuoteRequestForQuotationMeerkat ss = new ManageSupplierQuoteRequestForQuotationMeerkat(wsdlURL, SERVICE_NAME);
        ManageSupplierQuoteRequestForQuotation port = ss.getManageSupplierQuoteRequestForQuotationPort();  
        
        {
        System.out.println("Invoking calculateSupplierQuote...");
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.SupplierQuoteViewForCalculateSupplierQuoteRequest _calculateSupplierQuote_supplierQuote = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.SupplierQuoteViewForCalculateSupplierQuoteRequest();
        _calculateSupplierQuote_supplierQuote.setLocalCreationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-08-30T15:24:16.604+05:30"));
        _calculateSupplierQuote_supplierQuote.setLocalCallingSystem("WebALC");
        _calculateSupplierQuote_supplierQuote.setLocalBusinessOpportunityType("BO_7");
        _calculateSupplierQuote_supplierQuote.setLocalAccessType("AT_9");
        _calculateSupplierQuote_supplierQuote.setLocalRefId("GanestPOCtest0001");
        _calculateSupplierQuote_supplierQuote.setEndCustomerID("46680");
        _calculateSupplierQuote_supplierQuote.setEndCustomerName("ARROW");
        java.util.List<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.QuoteItem> _calculateSupplierQuote_supplierQuoteQuoteItem = new java.util.ArrayList<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.QuoteItem>();
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.QuoteItem _calculateSupplierQuote_supplierQuoteQuoteItemVal1 = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.QuoteItem();
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1.setQuoteItemID("GanestPOCtest0001");
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.OfferSpecification _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecification = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.OfferSpecification();
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecification.setOfferSpecificationCode("42");
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecification.setOfferSpecificationLabel("Business VPN Corporate");
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.Currency _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationCurrency = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.Currency();
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationCurrency.setCurrencyCode("USD");
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecification.setCurrency(_calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationCurrency);
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.CommitmentSpecification _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationCommitmentSpecification = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.CommitmentSpecification();
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationCommitmentSpecification.setDurationValue(1);
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationCommitmentSpecification.setDurationUnit("year");
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecification.setCommitmentSpecification(_calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationCommitmentSpecification);
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.ProductSpecification _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecification = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.ProductSpecification();
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecification.setProductSpecificationType("ME");
        java.util.List<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.FunctionSpecification> _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationFunctionSpecification = new java.util.ArrayList<com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.FunctionSpecification>();
        FunctionSpecification functionSpecification1 =new  FunctionSpecification();
        functionSpecification1.setFunctionSpecificationLabel("Speed");
        FunctionValueSpecification value = new FunctionValueSpecification();
        value.setFunctionValue("4000");
        functionSpecification1.setFunctionValueSpecification(value);
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationFunctionSpecification.add(functionSpecification1);
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecification.getFunctionSpecification().addAll(_calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationFunctionSpecification);
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.SubNetwork _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationSubNetwork = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.SubNetwork();
        java.util.List<java.lang.String> _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkSubNetworkID = new java.util.ArrayList<java.lang.String>();
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkSubNetworkID.add("BHXX01");
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkSubNetworkID.add("DCSX01");
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkSubNetworkID.add("LONT04");
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkSubNetworkID.add("LONX03");
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationSubNetwork.getSubNetworkID().addAll(_calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkSubNetworkID);
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.SubNetworkRole _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkSubNetworkRole = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.SubNetworkRole();
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkSubNetworkRole.setSubNetworkRoleName("POP");
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationSubNetwork.setSubNetworkRole(_calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationSubNetworkSubNetworkRole);
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecification.setSubNetwork(_calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecificationSubNetwork);
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecification.setProductSpecification(_calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecificationProductSpecification);
        _calculateSupplierQuote_supplierQuoteQuoteItemVal1.setOfferSpecification(_calculateSupplierQuote_supplierQuoteQuoteItemVal1OfferSpecification);
        _calculateSupplierQuote_supplierQuoteQuoteItem.add(_calculateSupplierQuote_supplierQuoteQuoteItemVal1);
        _calculateSupplierQuote_supplierQuote.getQuoteItem().addAll(_calculateSupplierQuote_supplierQuoteQuoteItem);
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.OperatorQuote _calculateSupplierQuote_supplierQuoteOperatorQuote = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.OperatorQuote();
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.QuoteItemOQ _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItem = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.QuoteItemOQ();
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.OfferSpecificationOQ _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemOfferSpecification = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.OfferSpecificationOQ();
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemOfferSpecification.setOfferSpecificationCode("42");
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemOfferSpecification.setOfferSpecificationLabel("Business VPN Corporate");
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemOfferSpecification.setOfferGrade("any");
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemOfferSpecification.setSymmetry("any");
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItem.setOfferSpecification(_calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemOfferSpecification);
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.Site _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSite = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.Site();
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSite.setSiteName("Customer Site");
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.Address _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddress = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.Address();
        String staircaseNumber=null;
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddress.setStaircaseNumber(staircaseNumber);
        String floorNumber=null;
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddress.setFloorNumber(floorNumber);
        String buildingName=null;
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddress.setBuildingName(buildingName);
        String residenceName=null;
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddress.setResidenceName(residenceName);
        String locality=null;
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddress.setLocality(locality);
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddress.setApartmentNumber("1");
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddress.setPostalCode("EC2Y9HU");
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.GeographicCoordinates _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressGeographicCoordinates = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.GeographicCoordinates();
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressGeographicCoordinates.setGeocodeX("51.5194266");
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressGeographicCoordinates.setGeocodeY("-0.08959600000002865");
        String geocodingSystems = null;
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressGeographicCoordinates.setGeocodingSystems(geocodingSystems);
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddress.setGeographicCoordinates(_calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressGeographicCoordinates);
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.Street _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressStreet = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.Street();
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressStreet.setStreetNumber("1");
        String streetLetter=null;
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressStreet.setStreetLetter(streetLetter);
        String streetType=null;
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressStreet.setStreetType(streetType);
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressStreet.setStreetName("1 Ropemaker St, London EC2Y 9HU, UK");
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddress.setStreet(_calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressStreet);
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.City _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressCity = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.City();
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressCity.setCityName("London");
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddress.setCity(_calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressCity);
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.State _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressState = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.State();
        String stateName=null;
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressState.setStateName(stateName);
        
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddress.setState(_calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressState);
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.Country _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressCountry = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.Country();
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressCountry.setCountryCode("GBR");
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddress.setCountry(_calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddressCountry);
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSite.setAddress(_calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSiteAddress);
        com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.PhoneNumber _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSitePhoneNumber = new com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.in.PhoneNumber();
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSitePhoneNumber.setNumber("0");
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSite.setPhoneNumber(_calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSitePhoneNumber);
        EmailAddress email = new EmailAddress();
        email.setEMailAddress(null);
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSite.setEmailAddress(email);
        
        _calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItem.setSite(_calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItemSite);
        _calculateSupplierQuote_supplierQuoteOperatorQuote.setQuoteItem(_calculateSupplierQuote_supplierQuoteOperatorQuoteQuoteItem);
        _calculateSupplierQuote_supplierQuote.setOperatorQuote(_calculateSupplierQuote_supplierQuoteOperatorQuote);
        try {
            com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.ebsmodel.csq.out.SupplierQuoteViewForCalculateSupplierQuoteResponse _calculateSupplierQuote__return = port.calculateSupplierQuote(_calculateSupplierQuote_supplierQuote);
            System.out.println("calculateSupplierQuote.result=" + _calculateSupplierQuote__return);

        } catch (CalculateSupplierQuoteFault e) { 
            System.out.println("Expected exception: CalculateSupplierQuoteFault has occurred.");
            System.out.println(e.toString());
        }
        }
        
        System.exit(0);
    }

}
