
package com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2017-09-01T11:27:22.378+05:30
 * Generated source version: 2.7.7
 */

@WebFault(name = "UpdateSupplierQuoteFault", targetNamespace = "http://www.orange.com/Meerkat/Interfaces/ManageSupplierQuote/RequestForQuotation/v1/message")
public class UpdateSupplierQuoteFault extends Exception {
    
    private com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.message.UpdateSupplierQuoteFault updateSupplierQuoteFault;

    public UpdateSupplierQuoteFault() {
        super();
    }
    
    public UpdateSupplierQuoteFault(String message) {
        super(message);
    }
    
    public UpdateSupplierQuoteFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UpdateSupplierQuoteFault(String message, com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.message.UpdateSupplierQuoteFault updateSupplierQuoteFault) {
        super(message);
        this.updateSupplierQuoteFault = updateSupplierQuoteFault;
    }

    public UpdateSupplierQuoteFault(String message, com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.message.UpdateSupplierQuoteFault updateSupplierQuoteFault, Throwable cause) {
        super(message, cause);
        this.updateSupplierQuoteFault = updateSupplierQuoteFault;
    }

    public com.orange.meerkat.interfaces.managesupplierquote.requestforquotation.v1.message.UpdateSupplierQuoteFault getFaultInfo() {
        return this.updateSupplierQuoteFault;
    }
}
