
package meerkatwsdlservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2017-08-30T12:09:45.617+05:30
 * Generated source version: 2.7.7
 * 
 */
public final class RequestHandler_RequestHandlerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://meerkatWSDLservice/", "RequestHandlerService");

    private RequestHandler_RequestHandlerPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RequestHandlerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RequestHandlerService ss = new RequestHandlerService(wsdlURL, SERVICE_NAME);
        RequestHandler port = ss.getRequestHandlerPort();  
        
        {
        System.out.println("Invoking serviceProvider...");
        meerkatwsdlservice.Parameter _serviceProvider_arg0 = new meerkatwsdlservice.Parameter();
        _serviceProvider_arg0.setBuldingNumber(662385090);
        _serviceProvider_arg0.setCity("City-1755784824");
        _serviceProvider_arg0.setCountry("Country-1649658540");
        _serviceProvider_arg0.setLatitude(677835183);
        _serviceProvider_arg0.setLoad(1934797441);
        _serviceProvider_arg0.setLongitude(-1396031057);
        _serviceProvider_arg0.setPostalCOde(-741065823);
        _serviceProvider_arg0.setService("Service-2091304438");
        _serviceProvider_arg0.setSpeed(-1594941425);
        _serviceProvider_arg0.setState("State312095948");
        _serviceProvider_arg0.setStreetName("StreetName1815027760");
        _serviceProvider_arg0.setTechnology("Technology-1651158235");
        java.lang.String _serviceProvider__return = port.serviceProvider(_serviceProvider_arg0);
        System.out.println("serviceProvider.result=" + _serviceProvider__return);


        }

        System.exit(0);
    }

}
