
package meerkatWSDLservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2017-08-30T12:06:19.233+05:30
 * Generated source version: 2.7.7
 * 
 */
 
public class RequestHandler_PortTypeServer{

    protected RequestHandler_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new meerkatWSDLservice.RequestHandler();
        String address = "http://localhost:9090/RequestHandlerPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new RequestHandler_PortTypeServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 